diffusion:
  model_type: 'dit'
  num_classes: 15
  target_channels: 3
  z_channels: 768
  depth: 16
  width: 2048
  num_sampling_steps: '1000'
  ema_decay: 0.999
  learn_sigma: false
  grad_checkpoint: false
  patch_size: 1
  channel_mult: [1,1,2,2]
  sigma_data: 4.5
  T: 1000
  N: 100
  timestep_scaling: 10
  loss_type: 'l2'
odm: 
  model_type: 'dit'
  num_classes: 15
  target_channels: 3
  z_channels: 768
  depth: 8
  width: 1024
  num_sampling_steps: '1000'
  ema_decay: 0.999
  learn_sigma: false
  grad_checkpoint: false
  patch_size: 1
  channel_mult: [1,1,2,2]
backbone: 
    model_type: efficientnet-b4
    outblocks:
      - 1
      - 5
      - 9
      - 21
    outstrides: 
      - 2
      - 4
      - 8
      - 16
    pretrained: true
    stride: 16
data:
  batch_size: 8
  category: all
  data_root: data/mpdd
  dataset_name: mpdd_all
  img_size: 224
  multi_category: false
  num_normal_samples: -1
  num_workers: 1
  pin_memory: true
  train: true
  transform_type: imagenet
optimizer:
  grad_clip: 1.0
  init_lr: 0.0001
  peak_lr: 0.0
  final_lr: 0.0
  num_epochs: 100
  optimizer_name: adam
  scheduler_type: const
  warmup_epochs: 0
  weight_decay: 0.0
logging:
  log_interval: 10
  save_interval: 50
  save_images: false
  save_dir: 'results/exp_dit_gigant_mpdd_enet_cm/all'
evaluation:
  eval_interval: 1
  eval_step: 2
meta:
  seed: 42
  device: 'cuda'