diffusion:
  model_type: 'dit'
  num_classes: 15
  target_channels: 3
  z_channels: 768
  depth: 8
  width: 2048
  num_sampling_steps: '100'
  ema_decay: 0.999
  learn_sigma: false
  grad_checkpoint: false
  patch_size: 1
  channel_mult: [1,1,2,2]
backbone: 
    model_type: efficientnet-b4
    outblocks: 
      - 1
      - 5
      - 9
      - 21
    outstrides: 
      - 2
      - 4
      - 8
      - 16
    pretrained: true
    stride: 16
data:
  batch_size: 8
  category: tile
  data_root: data/mvtec_ad
  dataset_name: mvtec_ad
  img_size: 256
  multi_category: false
  num_normal_samples: -1
  num_workers: 4
  pin_memory: true
  train: true
  transform_type: default
optimizer:
  grad_clip: 1.0
  init_lr: 0.000001
  peak_lr: 0.00005
  final_lr: 0.000005
  num_epochs: 1000
  optimizer_name: adamw
  scheduler_type: warmup_cosine
  warmup_epochs: 40
  weight_decay: 0
logging:
  log_interval: 10
  save_interval: 50
  save_images: false
  save_dir: 'results/exp_dit_hugew_ad_enet/tile'
evaluation:
  eval_interval: 50
  eval_step: 4
meta:
  seed: 42
  device: 'cuda'
